//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDK_GoiTap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChiTietDK_GoiTap()
        {
            this.BuoiTap = new HashSet<BuoiTap>();
        }
    
        public int id_CTDKGoiTap { get; set; }
        public Nullable<int> id_GT { get; set; }
        public Nullable<int> id_HV { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuoiTap> BuoiTap { get; set; }
        public virtual GoiTap GoiTap { get; set; }
        public virtual HoiVien HoiVien { get; set; }
    }
}
